version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ecotrack
      POSTGRES_USER: ecouser
      POSTGRES_PASSWORD: ecopassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecotrack-network

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecotrack-network

volumes:
  postgres_data:
  mongodb_data:

networks:
  ecotrack-network:
    driver: bridge